language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t scaredcat/docker-react -f Dockerfile.dev .

script:
  - docker run scaredcat/docker-react npm run test -- --coverage
