language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t scaredcat/docker-react -f Dockerfile.dev .

script:
  - docker run scaredcat/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-675049462793"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
